app:
  image:
    bucket: src\main\resources\images
spring:
  rabbitmq:
    host: localhost
    port: 5672
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_app
    username: chat_app
    password: chat_app
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb://chat_app:chat_app@localhost:27017/chat_app?authSource=admin
    redis:
      host: localhost
      port: 6379
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: update
    open-in-view: false
  mail:
    host: smtp.gmail.com 
    username:
    password:
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  session:
    store-type: redis
security:
  headers:
    cache: false
server:
  session:
    timeout: 800
broker:
  relay:
    host: localhost
    port: 61613
